### ISSUE TITLE
Redirecting to Empty Cart after successful payment instead of order confirmation

### ISSUE THREAD

**Issue by pratheekn91** [paytm/Paytm_Magento_Plugin#2]
HP cURL Version: 7.52.1
Magento Version: 2.3.4
Paytm Plugin Version: 2.0
Using the Porto theme 

After successful payment, expected outcome is order confirmation page is displayed with order number. 

Issue is after successful payment, customer is redirected to empty cart and Paytm Payment success message is displayed with no order confirmation or order number. 

Tough to recreate as it happen inconsistently, around 60% of the times only. Usually happens if customer takes too long to make payment.

Im using other payment modules too and happens only for Paytm payments.

**Comment by vishalpatel19862** [comment]
@pratheekn91 I am also facing same issue. It's because of google chrome browser's 'SameSite cookie' policy. Have you found any solution?

**Comment by pratheekn91** [comment]
No idea how same site policy causes this issue. But il check and see. 

I Didn't try finding a solution for this as I didn't have the time. I'm using alternate payment gateway which is not giving any issues. Il wait for the developers to fix this and get back to using Paytm. 

Could be because payments are taking too long and by the time the user comes back to the site, Magento session environment is expired.

**Comment by vishalpatel19862** [comment]
I had written email to Paytm support. they responded saying that issue is due to Chrome's policy change. I am using CCavenue and having similar issue with CCavenue as well.

**Comment by pratheekn91** [comment]
I'm using razorpay with their stock magento plugin and have not recived any
issues so far.

Let me check again and let me know if I can recreate the same issue with
razorpay plugin on chrome.

In the meantime can you confirm exactly which policy change is causing this
issue?


Regards,
Pratheek,
Probots,
www.probots.co.in
Ph: 9008620582

**Comment by vishalpatel19862** [comment]
As per new google chrome policy any third party module which is exchanging information between two different domain then it needs to have 'SameSite' cookie and requires to set value as None and label it as Secure.
If cookie and it's value is not updated as per new policy then it will not work.

**Comment by Jeeva-Rathinam** [comment]
@vishalpatel19862 Any hep thanks https://github.com/paytm/Paytm_Magento_Plugin/issues/3

**Comment by vishalpatel19862** [comment]
So far issue is not resolved. Paytm support team responded saying that our team is working to fix issue. They have not given any timeline so i have decided to disable.

**Comment by manikumaran1978** [comment]
We have same problem.
Only paytm success message without order number.
Also, there is no email is being sent to customer. Customer is getting confused whether order is confirmed or not
![paytm](https://user-images.githubusercontent.com/36991113/101135788-60263400-361d-11eb-9df3-0b5639347df6.jpg)

**Comment by manikumaran1978** [comment]
i have a new problem
![image](https://user-images.githubusercontent.com/36991113/101136479-7254a200-361e-11eb-9e81-3af11d7fcaea.png)

**Comment by pratheekn91** [comment]
> We have same problem.
> Only paytm success message without order number.
> Also, there is no email is being sent to customer. Customer is getting confused whether order is confirmed or not
> ![paytm](https://user-images.githubusercontent.com/36991113/101135788-60263400-361d-11eb-9df3-0b5639347df6.jpg)
> 

The Paytm extension does not support the latest 2.4

So it's best to not use it now. 

You will have to implement the API yourself till Paytm updates this extension to support the latest magento 2.4 version

**Comment by Knight017** [comment]
[Same issue with Amazon Payment , and there is one discussion related to {{block}} directive](https://github.com/amzn/amazon-payments-magento-2-plugin/issues/559#issuecomment-561414875) which may be reason here also.
Not sure this will help or not, it worked for me. 

I've commented the code which was sending the mail after order in `One97\Paytm\Observer\SendMailOnOrderSuccess.php`
however as @pratheekn91 mentioned in the first comment it is happening in 60% cases only. I've tested in some cases it working as of now.

Mostly it seems the reason only, will need to update email template to fix this.

**Comment by Knight017** [comment]
> **We are still observing this issue, with below implementation, however it is quite less, but still this is not a proper solution**

Fixed the issue by updating the cms block calling **{{block}}** directive by following stackoverflow question
[Magento2 checkout/onepage/success redirects to cart](https://magento.stackexchange.com/questions/251106/magento2-checkout-onepage-success-redirects-to-cart)

Reason explained by Paj

> If you use blocks in your email templates to load content from cms or phtml templates into new order emails this can cause an issue where the call to the block destroys the customer session when the new order email is sent. This means when you return to the site after successful third party payment i.e. PayPal there is no session data and the customer is redirected to an empty cart.

Solution given by Andrej Wasemiller

> This was with us after the PayPalPlus order, because of the static block in the email template.
> 
> instead of this in email template:
> 
> {{block cacheable="false" id="terms"}} 
> I created sales_email_order_terms.xml in Custom_Theme/Magento_Sales/layout.
> 
> <page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd" label="Email Terms" design_abstraction="custom">
>     <body>
>         <block class="Magento\Cms\Block\Block" name="block_email_terms" cacheable="false">
>             <arguments>
>                 <argument name="block_id" xsi:type="string">terms</argument>
>             </arguments>
>         </block>
>     </body>
> </page>
> and then use in email template:
> 
> {{layout handle="sales_email_order_terms"}}
>

**Comment by abpaytm** [comment]
Hi ,
Please use our latest plugin . https://github.com/paytm/Paytm_Magento_Plugin or download from magento market

**Comment by abpaytm** [comment]
Please try our latest plugin . If still you face any issue please mail to cmt.ops@paytm.com
