### ISSUE TITLE
Magento 2.3 - Create order from Backend - Invalid template file: 'One97_Paytm::form/paytm.phtml' in module: 'One97_Paytm' block's name: 'paytm'

### ISSUE THREAD

**Issue by Jeeva-Rathinam** [paytm/Paytm_Magento_Plugin#3]
How to solve the following error during creating order from backend

1 exception(s):
Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: 'One97_Paytm::form/paytm.phtml' in module: 'One97_Paytm' block's name: 'paytm'

Exception #0 (Magento\Framework\Exception\ValidatorException): Invalid template file: 'One97_Paytm::form/paytm.phtml' in module: 'One97_Paytm' block's name: 'paytm'
<pre>#1 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#2 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1103]
#3 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:673]
#4 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:564]
#5 Magento\Framework\View\Layout->_renderBlock('paytm') called at [vendor/magento/framework/View/Layout.php:540]
#6 Magento\Framework\View\Layout->renderNonCachedElement('paytm') called at [vendor/magento/framework/View/Layout.php:495]
#7 Magento\Framework\View\Layout->renderElement('paytm', true) called at [vendor/magento/framework/View/Element/AbstractBlock.php:520]
#8 Magento\Framework\View\Element\AbstractBlock->getChildHtml('payment.method.p...') called at [vendor/magento/module-sales/view/adminhtml/templates/order/create/billing/method/form.phtml:47]
#9 include('/var/www/html/gi...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#10 Magento\Framework\View\TemplateEngine\Php->render(&Magento\Sales\Block\Adminhtml\Order\Create\Billing\Method\Form#000000004d2ce9a8000000003ffab970#, '/var/www/html/gi...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
#11 Magento\Framework\View\Element\Template->fetchView('/var/www/html/gi...') called at [vendor/magento/framework/View/Element/Template.php:301]
#12 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#13 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1103]
#14 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:673]
#15 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:564]
#16 Magento\Framework\View\Layout->_renderBlock('order_create_bil...') called at [vendor/magento/framework/View/Layout.php:540]
#17 Magento\Framework\View\Layout->renderNonCachedElement('order_create_bil...') called at [vendor/magento/framework/View/Layout.php:495]
#18 Magento\Framework\View\Layout->renderElement('order_create_bil...', true) called at [vendor/magento/framework/View/Element/AbstractBlock.php:524]
#19 Magento\Framework\View\Element\AbstractBlock->getChildHtml('', true) called at [vendor/magento/module-sales/view/adminhtml/templates/order/create/abstract.phtml:15]
#20 include('/var/www/html/gi...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#21 Magento\Framework\View\TemplateEngine\Php->render(&Magento\Sales\Block\Adminhtml\Order\Create\Billing\Method#000000004d2ce9ab000000003ffab970#, '/var/www/html/gi...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
#22 Magento\Framework\View\Element\Template->fetchView('/var/www/html/gi...') called at [vendor/magento/framework/View/Element/Template.php:301]
#23 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/module-backend/Block/Template.php:129]
#24 Magento\Backend\Block\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#25 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1103]
#26 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:673]
#27 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:564]
#28 Magento\Framework\View\Layout->_renderBlock('billing_method') called at [vendor/magento/framework/View/Layout.php:540]
#29 Magento\Framework\View\Layout->renderNonCachedElement('billing_method') called at [vendor/magento/framework/View/Layout.php:495]
#30 Magento\Framework\View\Layout->renderElement('billing_method', true) called at [vendor/magento/framework/View/Element/AbstractBlock.php:520]
#31 Magento\Framework\View\Element\AbstractBlock->getChildHtml('billing_method') called at [vendor/magento/module-sales/view/adminhtml/templates/order/create/data.phtml:55]
#32 include('/var/www/html/gi...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#33 Magento\Framework\View\TemplateEngine\Php->render(&Magento\Sales\Block\Adminhtml\Order\Create\Data#000000004d2ce98b000000003ffab970#, '/var/www/html/gi...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
#34 Magento\Framework\View\Element\Template->fetchView('/var/www/html/gi...') called at [vendor/magento/framework/View/Element/Template.php:301]
#35 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/module-backend/Block/Template.php:129]
#36 Magento\Backend\Block\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#37 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1103]
#38 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:673]
#39 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:564]
#40 Magento\Framework\View\Layout->_renderBlock('data') called at [vendor/magento/framework/View/Layout.php:540]
#41 Magento\Framework\View\Layout->renderNonCachedElement('data') called at [vendor/magento/framework/View/Layout.php:495]
#42 Magento\Framework\View\Layout->renderElement('data', true) called at [vendor/magento/framework/View/Element/AbstractBlock.php:520]
#43 Magento\Framework\View\Element\AbstractBlock->getChildHtml('data') called at [vendor/magento/module-sales/view/adminhtml/templates/order/create/form.phtml:21]
#44 include('/var/www/html/gi...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#45 Magento\Framework\View\TemplateEngine\Php->render(&Magento\Sales\Block\Adminhtml\Order\Create\Form\Interceptor#000000004d2ce8d4000000003ffab970#, '/var/www/html/gi...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
#46 Magento\Framework\View\Element\Template->fetchView('/var/www/html/gi...') called at [vendor/magento/framework/View/Element/Template.php:301]
#47 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/module-backend/Block/Template.php:129]
#48 Magento\Backend\Block\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#49 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1103]
#50 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:673]
#51 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:564]
#52 Magento\Framework\View\Layout->_renderBlock('order_create_for...') called at [vendor/magento/framework/View/Layout.php:540]
#53 Magento\Framework\View\Layout->renderNonCachedElement('order_create_for...') called at [vendor/magento/framework/View/Layout.php:495]
#54 Magento\Framework\View\Layout->renderElement('order_create_for...', true) called at [vendor/magento/framework/View/Element/AbstractBlock.php:520]
#55 Magento\Framework\View\Element\AbstractBlock->getChildHtml('form') called at [vendor/magento/module-backend/Block/Widget/Form/Container.php:197]
#56 Magento\Backend\Block\Widget\Form\Container->getFormHtml() called at [vendor/magento/module-backend/view/adminhtml/templates/widget/form/container.phtml:22]
#57 include('/var/www/html/gi...') called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]
#58 Magento\Framework\View\TemplateEngine\Php->render(&Magento\Sales\Block\Adminhtml\Order\Create#000000004d2ce8ad000000003ffab970#, '/var/www/html/gi...', array()) called at [vendor/magento/framework/View/Element/Template.php:271]
#59 Magento\Framework\View\Element\Template->fetchView('/var/www/html/gi...') called at [vendor/magento/framework/View/Element/Template.php:301]
#60 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/module-backend/Block/Template.php:129]
#61 Magento\Backend\Block\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#62 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1103]
#63 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:673]
#64 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:564]
#65 Magento\Framework\View\Layout->_renderBlock('order_content') called at [vendor/magento/framework/View/Layout.php:540]
#66 Magento\Framework\View\Layout->renderNonCachedElement('order_content') called at [vendor/magento/framework/View/Layout.php:495]
#67 Magento\Framework\View\Layout->renderElement('order_content', false) called at [vendor/magento/framework/View/Layout.php:592]
#68 Magento\Framework\View\Layout->_renderContainer('content', false) called at [vendor/magento/framework/View/Layout.php:542]
#69 Magento\Framework\View\Layout->renderNonCachedElement('content') called at [vendor/magento/framework/View/Layout.php:495]
#70 Magento\Framework\View\Layout->renderElement('content', false) called at [vendor/magento/framework/View/Layout.php:592]
#71 Magento\Framework\View\Layout->_renderContainer('main.col', false) called at [vendor/magento/framework/View/Layout.php:542]
#72 Magento\Framework\View\Layout->renderNonCachedElement('main.col') called at [vendor/magento/framework/View/Layout.php:495]
#73 Magento\Framework\View\Layout->renderElement('main.col', false) called at [vendor/magento/framework/View/Layout.php:592]
#74 Magento\Framework\View\Layout->_renderContainer('admin.scope.col....', false) called at [vendor/magento/framework/View/Layout.php:542]
#75 Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col....') called at [vendor/magento/framework/View/Layout.php:495]
#76 Magento\Framework\View\Layout->renderElement('admin.scope.col....', false) called at [vendor/magento/framework/View/Layout.php:592]
#77 Magento\Framework\View\Layout->_renderContainer('page.main.contai...', false) called at [vendor/magento/framework/View/Layout.php:542]
#78 Magento\Framework\View\Layout->renderNonCachedElement('page.main.contai...') called at [vendor/magento/framework/View/Layout.php:495]
#79 Magento\Framework\View\Layout->renderElement('page.main.contai...', false) called at [vendor/magento/framework/View/Layout.php:592]
#80 Magento\Framework\View\Layout->_renderContainer('page.content', false) called at [vendor/magento/framework/View/Layout.php:542]
#81 Magento\Framework\View\Layout->renderNonCachedElement('page.content') called at [vendor/magento/framework/View/Layout.php:495]
#82 Magento\Framework\View\Layout->renderElement('page.content', false) called at [vendor/magento/framework/View/Layout.php:592]
#83 Magento\Framework\View\Layout->_renderContainer('page.wrapper', false) called at [vendor/magento/framework/View/Layout.php:542]
#84 Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper') called at [vendor/magento/framework/View/Layout.php:495]
#85 Magento\Framework\View\Layout->renderElement('page.wrapper', false) called at [vendor/magento/framework/View/Layout.php:592]
#86 Magento\Framework\View\Layout->_renderContainer('backend.page', false) called at [vendor/magento/framework/View/Layout.php:542]
#87 Magento\Framework\View\Layout->renderNonCachedElement('backend.page') called at [vendor/magento/framework/View/Layout.php:495]
#88 Magento\Framework\View\Layout->renderElement('backend.page', false) called at [vendor/magento/framework/View/Layout.php:592]
#89 Magento\Framework\View\Layout->_renderContainer('root', false) called at [vendor/magento/framework/View/Layout.php:542]
#90 Magento\Framework\View\Layout->renderNonCachedElement('root') called at [vendor/magento/framework/View/Layout.php:495]
#91 Magento\Framework\View\Layout->renderElement('root') called at [vendor/magento/framework/View/Layout.php:961]
#92 Magento\Framework\View\Layout->getOutput() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:37]
#93 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:258]
#94 Magento\Framework\View\Result\Page->render(&Magento\Framework\App\Response\Http\Interceptor#000000004d2ce0a3000000003ffab970#) called at [vendor/magento/framework/View/Result/Layout.php:171]
#95 Magento\Framework\View\Result\Layout->renderResult(&Magento\Framework\App\Response\Http\Interceptor#000000004d2ce0a3000000003ffab970#) called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:24]
#96 Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(&Magento\Framework\App\Response\Http\Interceptor#000000004d2ce0a3000000003ffab970#) called at [vendor/magento/framework/App/Http.php:120]
#97 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#98 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#000000004d2ce0a1000000003ffab970#) called at [pub/index.php:43]
</pre>

**Comment by abpaytm** [comment]
please try our latest plugin
