### ISSUE TITLE
Deprecated Functionality: Array and string offset access syntax with curly braces is deprecated 

### ISSUE THREAD

**Issue by manikumaran1978** [paytm/Paytm_Magento_Plugin#5]
Deprecated Functionality: Array and string offset access syntax with curly braces is deprecated in app/code/One97
  /Paytm/Helper/Data.php on line 196

**Comment by manikumaran1978** [comment]
Php 7.4 issue
https://github.com/squizlabs/PHP_CodeSniffer/issues/2558

changing line 196 in file
app/code/One97/Paytm/Helper/Data.php

from  this
$pad = ord($text{strlen($text) - 1});
to
$pad = ord($text[strlen($text) - 1]);
solved the problem

**Comment by amitcoders** [comment]
$pad = ord($text[strlen($text) - 1]);
