### ISSUE TITLE
On closing Paytm payment popup cart became empty and pay button still remains disabled

### ISSUE THREAD

**Issue by Knight017** [paytm/Paytm_Magento_Plugin#6]
When we click to pay button of paytm payment method, a popup opened but when we click the top left cross button on popup, than the cart became empty and payment button for paytm still remains close.

![paytm-cancel-issue](https://user-images.githubusercontent.com/18218393/113480490-11e14e80-94b2-11eb-8063-fa5ff8b2f5b7.png)

I think the cart should have the all items and the button also should be enabled so that the customer can choose paytm again.

**Comment by abpaytm** [comment]
Hi please update with our latest plugin https://github.com/paytm/Paytm_Magento_Plugin/tree/master/Magento_V2.3x

**Comment by Knight017** [comment]
But still if user click on close button then cart became empty, means user can't choose another payment method or go to the other page to add new products.

**Comment by rahul2bisht** [comment]
Hi,
Please update the plugin from  https://github.com/paytm/Paytm_Magento_Plugin/tree/master/Magento_V2.3x
and try again as the issue raised by you is solved in this updated plugin.
If you still face issue you can get in touch with us 
https://business.paytm.com/contact-us#developer
