### ISSUE TITLE
On Checkout Iframe is not loading with 500 Error

### ISSUE THREAD

**Issue by Knight017** [paytm/Paytm_Magento_Plugin#8]
We are using Magento 2.4.1 and installed latest Paytm Module, but on checkout page the Iframe is not loading, it is throwing following error with 500 status code.

`1 exception(s):
Exception #0 (Exception): Notice: Undefined index: txnToken in app/code/One97/Paytm/Model/Paytm.php on line 159

Exception #0 (Exception): Notice: Undefined index: txnToken in app/code/One97/Paytm/Model/Paytm.php on line 159
<pre>#1 One97\Paytm\Model\Paytm->buildPaytmRequest(&Magento\Sales\Model\Order\Interceptor#0000000046d3d3ee000000007a884ed8#) called at [generated/code/One97/Paytm/Model/Paytm/Interceptor.php:63]
#2 One97\Paytm\Model\Paytm\Interceptor->buildPaytmRequest(&Magento\Sales\Model\Order\Interceptor#0000000046d3d3ee000000007a884ed8#) called at [app/code/One97/Paytm/Controller/Standard/Redirect.php:27]
#3 One97\Paytm\Controller\Standard\Redirect->execute() called at [generated/code/One97/Paytm/Controller/Standard/Redirect/Interceptor.php:50]
#4 One97\Paytm\Controller\Standard\Redirect\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:108]
#5 Magento\Framework\App\Action\Action->dispatch(&Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#6 One97\Paytm\Controller\Standard\Redirect\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#7 One97\Paytm\Controller\Standard\Redirect\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#8 One97\Paytm\Controller\Standard\Redirect\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#), array(array('designLoader', 'customerNotifica...', 'catalog_app_acti...', 'tax-app-action-d...', 'weee-app-action-...', 'storeCheck', 'contextPlugin', 'customer-app-act...'))) called at [generated/code/One97/Paytm/Controller/Standard/Redirect/Interceptor.php:65]
#9 One97\Paytm\Controller\Standard\Redirect\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#) called at [vendor/magento/framework/App/FrontController.php:162]
#10 Magento\Framework\App\FrontController->processRequest(&Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#, &One97\Paytm\Controller\Standard\Redirect\Interceptor#0000000046d3d75a000000007a884ed8#) called at [vendor/magento/framework/App/FrontController.php:98]
#11 Magento\Framework\App\FrontController->dispatch(&Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#12 Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', array(&Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#13 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#) called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#14 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000046d3d54b000000007a884ed8#, &Closure#0000000046d3d562000000007a884ed8#, &Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#15 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#) called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:69]
#16 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(&Magento\Framework\App\FrontController\Interceptor#0000000046d3d54b000000007a884ed8#, &Closure#0000000046d3d562000000007a884ed8#, &Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#) called at [vendor/magento/framework/Interception/Interceptor.php:135]
#17 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#18 Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', array(&Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#), NULL) called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]
#19 Magento\Framework\App\FrontController\Interceptor->dispatch(&Magento\Framework\App\Request\Http#0000000046d3d4d8000000007a884ed8#) called at [vendor/magento/framework/App/Http.php:116]
#20 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:24]
#21 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]
#22 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000046d3d4cb000000007a884ed8#) called at [index.php:39]
`

Please look this , as it has stopped payment.

**Comment by rahul2bisht** [comment]
Hi 
please update the data.php file in Helper and mark APPEND_TIMESTAMP as true.
It will solve your issue.
